config/routes.rb
Rails.application.routes.draw do

root 'companies#index'

 resources :companies do
	resources :messages

 end
end

app/models/company.rb
class Company < ActiveRecord::Base
	has_many :messages
end 

app/models/message.rb
class Message < ActiveRecord::Base
	belongs_to :company
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
	
	before_action :single_company, only: [:show, :edit, :update, :destroy]

	def index
		@companies = Company.all
	end

	def show
		@message = Message.new
	end

	def edit
	end

	def new
		@company = Company.new
	end

	def create
		@company = Company.new(company_params)
		save(@company)
	end

	def update
		@company = Company.update(company_params)
		save(@company)
	end

	private

	def save(company)
		if company.save
			redirect_to '/'
		else
			render :new
		end
	end

	def single_company
		@company = Company.find(params[:id])
	end

	def company_params
		params.require(:company).permit(:name, :desc, :website)
	end
end 

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	before_action :single_message, only: [:show, :edit, :update, :destroy]

	def index
		@messages = Message.all
	end

	def show
	end

	def edit
	end

	def new
		@message = Message.new
		@company = Company.find(params[:id])
	end

	def create
		@message = Message.new(message_params)
		save(@message)
	end

	def update
		@message = Message.update(message_params)
		save(@message)
	end

	private

	def save(message)
		if message.save
			redirect_to message.company
		else
			render :new
		end
	end

	def single_message
		@message = Message.find(params[:id])
	end

	def message_params
		params.require(:message).permit(:body, :author, :company_id)
	end
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/companies/_form.html.erb
<%= form_for @company do |f| %>
	<%= f.text_field :name %>
	<%= f.text_area :desc %>
	<%= f.text_field :website %>
	<%= f.submit %>    
<% end %> 
 

app/views/companies/edit.html.erb
<%= render '_form' %> 

app/views/companies/index.html.erb
<section>
	<% @companies.each do |company| %>
		<div>
			<h2> <%= link_to company.name, company.id%></h2>
			<ul class="links">
			<li> <%= link_to 'Send love', new_company_message_path(company_id: company.id) %> </li>
			<li> <%= link_to 'Visit their website', company.website %> </li>
			</li> 	
		</div>
	<% end %>  
</section>

app/views/companies/new.html.erb
<%= render '_form' %> 

app/views/companies/show.html.erb
<h2><%= @company.name%> </h2>
<p> <%= @company.desc %>  </p>

<%= render 'partials/form_message' %> 
<ul>
	<% @company.messages.each do |message| %>
	<li> <%= message.body %> by <%= message.author %>  </li>
	<% end %> 
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Linkedout</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
	<h1> <%= link_to 'LinkedOut', '/' %>  <small> Where prospective employees share their interest </small> </h1>
</header>

<%= yield %>

</body>
</html>

app/views/messages/new.html.erb
<%= render 'partials/form_message' %> 

app/views/partials/_form_message.html.erb
<%= form_for @message do |f|%>
<%= f.hidden_field :company_id %> 
<%= f.text_area :body %>
<%= f.text_field :author %>  
<%= f.submit %> 
<% end %>  